pipeline {
  agent {
    kubernetes {
      yaml """
apiVersion: v1
kind: Pod
spec:
  serviceAccountName: jenkins
  containers:
    - name: kaniko
      image: gcr.io/kaniko-project/executor:latest
      command: ["/busybox/cat"]
      tty: true
      volumeMounts:
        - name: docker-config
          mountPath: /kaniko/.docker
  volumes:
    - name: docker-config
      secret:
        secretName: dockerhub-dockercfg
"""
    }
  }

  environment {
    IMAGE = "docker.io/wonseokk123/stock101-be"
    TAG   = "${env.GIT_COMMIT.take(7)}"
  }

  triggers { githubPush() }

  stages {
    stage('Checkout') {
      steps { checkout scm }
    }

    stage('Build & Push (Kaniko)') {
      steps {
        container('kaniko') {
          sh """
            /kaniko/executor \
              --context=`pwd` \
              --dockerfile=Dockerfile \
              --destination=${IMAGE}:${TAG} \
              --destination=${IMAGE}:latest
          """
        }
      }
    }
  }

  post {
    success { echo "✅ Pushed: ${IMAGE}:${TAG}" }
    failure { echo "❌ Failed" }
  }
}