apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend-app
  namespace: argocd
  annotations:

    argocd-image-updater.argoproj.io/image-list: frontend=iiijjong/frontend

    argocd-image-updater.argoproj.io/frontend.update-strategy: latest

    argocd-image-updater.argoproj.io/write-back-method: git

    argocd-image-updater.argoproj.io/git-branch: main
    argocd-image-updater.argoproj.io/git-repo: https://github.com/IIIjong/frontend-gitops.git

    argocd-image-updater.argoproj.io/secret-ref: dockerhub-credentials

    argocd-image-updater.argoproj.io/frontend.allow-tags: regexp:^\\d+$
spec:
  project: default
  source:
    repoURL: https://github.com/IIIjong/frontend-gitops.git
    targetRevision: main
    path: k8s/frontend
  destination:
    server: https://kubernetes.default.svc
    namespace: frontend
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
