spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST}
      port: ${SPRING_DATA_REDIS_PORT}
      password: ${SPRING_DATA_REDIS_PASSWORD}

mybatis:
  type-aliases-package: com.monstersinc.stock101.*.model.vo
  mapper-locations:
    - classpath:mappers/**/*.xml
  configuration:
    jdbc-type-for-null: NULL

springdoc:
  swagger-ui:
    operations-sorter: method
  paths-to-match:
    - /api/v1/**

jwt:
  issuer: ${JWT_ISSUER}
  secret: ${JWT_SECRET}

apikey:
  stock-key: ${APIKEY_STOCK_KEY}
  kis-key: ${APIKEY_KIS_KEY}
  kis-secret: ${APIKEY_KIS_SECRET}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
